---
- name: Include Distro Specific Vars
  include_vars: "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"

- name: Create Aerospike download directory.
  file:
    path: "{{ aerospike_source_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create Aerospike log directory.
  file:
    path: "{{ aerospike_log_directory }}"
    state: directory

## Aerospike site does not have SSL
- name: Download Aerospike package.
  unarchive:
    src: "{{ aerospike_download_url }}"
    dest: "{{ aerospike_source_directory }}"
    remote_src: True
    validate_certs: no

- name: Get Names of Aerospike RPM Packages.
  find:
    paths: "{{ aerospike_source_directory }}/{{ aerospike_package_name }}"
    patterns: "^(aerospike-(?:server|tools).+\\.rpm)$"
    use_regex: true
  register: aerospike_rpms

- name: Install Aerospike package from rpm.
  yum:
    name: "{{ item.path }}"
    state: present
  with_items:
    - "{{ aerospike_rpms.files }}"
  notify:
    - start aerospike
  when: ansible_os_family == 'RedHat'

- name: Get Names of Aerospike DEB Packages.
  find:
    paths: "{{ aerospike_source_directory }}/{{ aerospike_package_name }}"
    patterns: "^(aerospike-(?:server|tools).+\\.deb)$"
    use_regex: true
  register: aerospike_debs

- name: Install Aerospike package from deb.
  apt:
    deb: "{{ item.path }}"
    install_recommends: yes
  with_items:
    - "{{ aerospike_debs.files }}"
  notify:
    - start aerospike
  when: ansible_os_family == 'Debian'

- name: Place Aerospike configuration file.
  template:
    src: aerospike.conf.j2
    dest: "{{ aerospike_config_destination }}"
    owner: root
    group: root
    force: yes
  notify:
    - start aerospike
