---
- name: Start aerospike service Centos/RedHat 7 and Amazon
  systemd:
    name: aerospike
    state: restarted
    enabled: yes
  when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7') or
        (ansible_distribution == 'Red Hat Enterprise Linux' and ansible_distribution_major_version == '7') or
        (ansible_distribution == 'Amazon') or
        (ansible_distribution == 'Debian' and ansible_distribution_major_version == '8')
  listen: start aerospike

- name: Start aerospike service Centos/RedHat 6
  service:
    name: aerospike
    state: restarted
    enabled: yes
  when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6') or
        (ansible_distribution == 'Red Hat Enterprise Linux' and ansible_distribution_major_version == '6') or
        (ansible_distribution == 'Debian' and ansible_distribution_major_version == '7')
  listen: start aerospike

- name: Make Sure Cluster Memembership Is Correct
  command: asinfo --no-config-file
  register: asinfo_output
  until: asinfo_output.stdout.find("cluster_size={{ aerospike_cluster_size }}") != -1
  retries: 100
  delay: 5
  ignore_errors: true
  listen: start aerospike